//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APLICACAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GRC_TAB_CL
    {
        public int Id { get; set; }
        public string no { get; set; }
        public string nome { get; set; }
        public string ncont { get; set; }
        public string Bloqueado { get; set; }
        public Nullable<decimal> Plafond { get; set; }
        public Nullable<System.DateTime> DT_ACT { get; set; }
        public string Dias_Pagamento { get; set; }
        public string Zona { get; set; }
        public string Tipo_Pagamento { get; set; }
        public string Comercial { get; set; }
        public string Class_05 { get; set; }
        public string Plafond_Seguro { get; set; }
        public string Saldo { get; set; }
    }
}
