//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APLICACAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GRC_ONL_FT_PER_CAUTIO
    {
        public string no { get; set; }
        public Nullable<decimal> Fact_Per_1 { get; set; }
        public Nullable<decimal> Fact_Per_2 { get; set; }
        public Nullable<decimal> Fact_Per_3 { get; set; }
        public Nullable<decimal> Fact_Per_4 { get; set; }
        public Nullable<decimal> Fact_Per_5 { get; set; }
        public Nullable<decimal> Fact_Per_6 { get; set; }
        public Nullable<decimal> Fact_Per_7 { get; set; }
        public Nullable<decimal> Fact_Per_8 { get; set; }
        public Nullable<decimal> Fact_Per_9 { get; set; }
        public Nullable<decimal> Fact_Per_10 { get; set; }
        public Nullable<decimal> Fact_Per_11 { get; set; }
        public Nullable<decimal> Fact_Per_12 { get; set; }
        public Nullable<decimal> Fact_Per_13 { get; set; }
        public Nullable<decimal> Fact_Per_14 { get; set; }
        public Nullable<decimal> Fact_Per_15 { get; set; }
        public Nullable<decimal> Fact_Per_16 { get; set; }
        public Nullable<decimal> Fact_Per_17 { get; set; }
        public Nullable<decimal> Fact_Per_18 { get; set; }
        public Nullable<decimal> Fact_Per_19 { get; set; }
        public Nullable<decimal> Fact_Per_20 { get; set; }
        public Nullable<decimal> Fact_Per_21 { get; set; }
        public Nullable<decimal> Fact_Per_22 { get; set; }
        public Nullable<decimal> Fact_Per_23 { get; set; }
        public Nullable<decimal> Fact_Per_24 { get; set; }
        public Nullable<decimal> Fact_Per_25 { get; set; }
    }
}
