//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APLICACAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GRC_FACTURACAO
    {
        public int Id { get; set; }
        public string no { get; set; }
        public Nullable<System.DateTime> data_doc { get; set; }
        public Nullable<System.DateTime> data_venc { get; set; }
        public Nullable<decimal> valor_base { get; set; }
        public Nullable<decimal> total_iva { get; set; }
        public Nullable<decimal> total_doc { get; set; }
    }
}
