//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APLICACAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GRC_CM_CL_CLIENTES
    {
        public int Id { get; set; }
        public string no { get; set; }
        public string nome { get; set; }
        public string ncont { get; set; }
        public string conta { get; set; }
        public Nullable<decimal> edeb { get; set; }
        public Nullable<decimal> ecred { get; set; }
        public string deb_cred { get; set; }
        public Nullable<System.DateTime> datalc { get; set; }
        public Nullable<System.DateTime> datavenc { get; set; }
        public string Class_04 { get; set; }
    }
}
