//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APLICACAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GRC_ONL_CC_IDADE_SALDOS
    {
        public string no { get; set; }
        public Nullable<decimal> edeb___INT1_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT2_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT3_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT4_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT5_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT6_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT7_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT8_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT9_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT10_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT11_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT12_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT13_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT1___N_1_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT2___N_1_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT3___N_1_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT4___N_1_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT5___N_1_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT6___N_1_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT7___N_1_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT8___N_1_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT9___N_1_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT10___N_1_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT11___N_1_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT12___N_1_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT13___N_1_DT_CONT { get; set; }
        public Nullable<decimal> ecred___N_DT_CONT { get; set; }
        public Nullable<decimal> ecred___N_1_DT_CONT { get; set; }
        public Nullable<decimal> edeb___INT1_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT2_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT3_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT4_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT5_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT6_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT7_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT8_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT9_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT10_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT11_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT12_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT13_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT1___N_1_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT2___N_1_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT3___N_1_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT4___N_1_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT5___N_1_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT6___N_1_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT7___N_1_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT8___N_1_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT9___N_1_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT10___N_1_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT11___N_1_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT12___N_1_DT_VENC { get; set; }
        public Nullable<decimal> edeb___INT13___N_1_DT_VENC { get; set; }
        public Nullable<decimal> ecred___N_DT_VENC { get; set; }
        public Nullable<decimal> ecred___N_1_DT_VENC { get; set; }
    }
}
